### ISSUE TITLE
Add Topics

### ISSUE THREAD

**Issue by ericdrosado** [amandp13/Cool-Scripts-Python-Nerds#87]
In Community Exchange, GitHub Topics will help the discoverability of your project. I see that you already have some topics, but I would consider adding a few more to help others find your project.

**Comment by amandp13** [comment]
Sure @ericdrosado It's your repo now 😊, you are welcome to add more issues to help others.

**Comment by ericdrosado** [comment]
@amandp13 this repo will always be your repo 😄 . We just want to help more students find it because it brings so much value to the community. 

I'll go ahead and close this issue since you have GitHub Topics:

![Screen Shot 2022-05-18 at 3 16 47 PM](https://user-images.githubusercontent.com/10368374/169148233-acae344e-cca0-48ba-a932-50e5f93c5a14.png)
