### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by ericdrosado** [amandp13/Cool-Scripts-Python-Nerds#88]
A README is often the first item a visitor will see when visiting your repository. Your README looks pretty good at the moment. I would recommend your README includes:

* A reference to your LEARN.md
* Mention your code of conduct

**Comment by amandp13** [comment]
Hi @ericdrosado Yes, As you told, There is already a reference to the **Learn.md** file as **contributions.md** 
Screen Print is attached.

![image](https://user-images.githubusercontent.com/55224891/168885680-26abfbce-df05-4d99-bb72-549e486674cd.png)

And I have added the code of conduct as well as you told, do check below.

![image](https://user-images.githubusercontent.com/55224891/168887624-72c0b254-582d-4034-bd38-7ac895a900cd.png)

**Comment by ericdrosado** [comment]
If you decide to create a table of contents for LEARN.md, I would recommend adding it. If you would rather not be designated as a `learn` repo, and you just want to be a `collaborate` repo, feel free to close this issue.

**Comment by amandp13** [comment]
Hey @ericdrosado, It would be great if this would be just a **collaborated** repo 😊. I am closing this issue now. Thank you.
