### ISSUE TITLE
Add templates for issues

### ISSUE THREAD

**Issue by ericdrosado** [amandp13/Cool-Scripts-Python-Nerds#89]
Issue templates are very helpful for a collaboration repo. When users identify a bug or want to add a new feature, you can provide templates so you can collect all the pertinent information you need to fix a bug or add a new feature. 

We recommend creating a “Report Bug” and “Feature Request” issue template. 

Some suggested prompts/questions you can add to a “Report Bug” template are:

* Briefly describe the bug
* What is the expected behavior?
* Please provide step by step instructions on how to reproduce the bug

Some suggested prompts/questions you can add to a “Feature Request” issue template are:

* Briefly describe your feature request
* What problem is this feature trying to solve?
* How do we know when the feature is complete?

**Comment by amandp13** [comment]
Hi @ericdrosado Added the required templates, Do check and review.

![image](https://user-images.githubusercontent.com/55224891/168893616-854f22ab-82b9-440d-bfb2-b3742a5e42fa.png)

**Comment by ericdrosado** [comment]
Both templates look great! 🚀
