### ISSUE TITLE
Any Suggestions is welcomed.

### ISSUE THREAD

**Issue by amandp13** [amandp13/Cool-Scripts-Python-Nerds#9]
### Any changes or suggestions would be quite helpful for this repo and to others.
- Comment here 
- Thanks in advance.

**Comment by mrjeevan** [comment]
could i add these?
[mrjeevan](https://github.com/mrjeevan/Python_Stuff)

**Comment by amandp13** [comment]
@mrjeevan Yes, would love that

**Comment by mrjeevan** [comment]
@amandp13  Done, it wold be great if u merge pull request.
